# Generated by Django 4.0.6 on 2022-10-07 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artImage', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='art_photos')),
                ('content', models.TextField()),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('watches', 'Watches'), ('other', 'Other')], max_length=38)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bookmarks', models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('downvote', models.ManyToManyField(related_name='down', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('upvote', models.ManyToManyField(related_name='up', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
