# Generated by Django 4.0.6 on 2022-10-08 09:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artImage',
            field=models.ImageField(blank=True, default='./images/default.jpg', null=True, upload_to='art_photos'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('javascript', 'JavaScript'), ('webdevelpment', 'Web Develpment'), ('react', 'React'), ('python', 'Python'), ('other', 'Other')], max_length=43),
        ),
    ]
