# Generated by Django 4.0.6 on 2022-10-09 15:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_artimage_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('javascript', 'JavaScript'), ('web develpment', 'Web Develpment'), ('react', 'React'), ('python', 'Python'), ('other', 'Other')], max_length=44),
        ),
    ]
