# Generated by Django 4.0.6 on 2022-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(default='Clic to see blog', max_length=200),
            preserve_default=False,
        ),
    ]
